name: ' ' # empty name
on: [push, pull_request, workflow_dispatch]

jobs:
  broken-ideal:
    runs-on: ubuntu-24.04-arm
    container:
      image: termux/termux-docker:aarch64
    steps:
      - name: setup
        run: |
          /entrypoint.sh pkg install -y ninja clang python git
          # /entrypoint.sh pip install meson
      - uses: actions/checkout@v6.0.1
      - name: build
        run: touch artifact
      - uses: actions/upload-artifact@v6.0.0
        if: always()
        with:
          name: artifact
          path: artifact

