name: ' ' # empty name
on: [push, pull_request, workflow_dispatch]

jobs:
  working:
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Release, Debug ]
        architecture: [ aarch64, x86_64 ]
        include:
          - architecture: aarch64
            runner: ubuntu-24.04-arm
          - architecture: x86_64
            runner: ubuntu-24.04
    runs-on: ${{matrix.runner}}
    container:
      image: termux/termux-docker:${{matrix.architecture}}
      volumes: 
        - /tmp/node20:/__e/node20
    env:
      TERMUX_MAIN_PACKAGE_FORMAT: debian
      ANDROID_ROOT: /system
      ANDROID_DATA: /data
      PREFIX: /data/data/com.termux/files/usr
      HOME: /data/data/com.termux/files/home
      PATH: /data/data/com.termux/files/usr/bin
      TMPDIR: /data/data/com.termux/files/usr/tmp
      LANG: en_US.UTF-8
      TZ: UTC
    steps:
      - name: prepare container
        run: |
          ln -sf ${PREFIX}/etc/termux/mirrors/default ${PREFIX}/etc/termux/chosen_mirrors
          /entrypoint.sh pkg update
          /entrypoint.sh bash -c "yes | pkg upgrade -y"
          chmod -R o+x ${PREFIX}/bin
          /entrypoint.sh pkg install -y nodejs-lts
          ln -sf ${PREFIX}/bin /__e/node20/bin
      - uses: actions/checkout@v4.2.2
      - name: fix permissions after checkout (checkout runs as root and entrypoint.sh switches to user 1000)
        run: chown -R 1000:1000 .

      - name: setup
        run: /entrypoint.sh pkg install -y llvm binutils binutils libgc build-essential cmake llvm git libedit zlib clang make mlir llvm-tools libpolly python libllvm-static libandroid-execinfo
      - name: build
        run: |
          git clone https://github.com/Book-reader/c3c -b fix-termux
          mv c3c/* .
          cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
          make -C build -j$(nproc)

      - name: Compile and run some examples
        run: |
          cd resources
          ../build/c3c compile examples/base64.c3
          ../build/c3c compile examples/binarydigits.c3
          ../build/c3c compile examples/brainfk.c3
          ../build/c3c compile examples/factorial_macro.c3
          ../build/c3c compile examples/fasta.c3
          ../build/c3c compile examples/gameoflife.c3
          ../build/c3c compile examples/hash.c3
          ../build/c3c compile-only examples/levenshtein.c3
          ../build/c3c compile examples/load_world.c3
          ../build/c3c compile-only examples/map.c3
          ../build/c3c compile examples/mandelbrot.c3
          ../build/c3c compile examples/plus_minus.c3
          ../build/c3c compile examples/nbodies.c3
          ../build/c3c compile examples/spectralnorm.c3
          ../build/c3c compile examples/swap.c3
          ../build/c3c compile examples/contextfree/boolerr.c3
          ../build/c3c compile examples/contextfree/dynscope.c3
          ../build/c3c compile examples/contextfree/guess_number.c3
          ../build/c3c compile examples/contextfree/multi.c3
          ../build/c3c compile examples/contextfree/cleanup.c3
          ../build/c3c compile-run examples/hello_world_many.c3
          ../build/c3c compile-run examples/time.c3
          ../build/c3c compile-run examples/fannkuch-redux.c3
          ../build/c3c compile-run examples/contextfree/boolerr.c3
          ../build/c3c compile-run examples/load_world.c3
          ../build/c3c compile-run examples/process.c3
          ../build/c3c compile-run examples/ls.c3
          ../build/c3c compile-run examples/args.c3 -- foo -bar "baz baz"

      - name: Compile and run staticlib-test
        run: |
          cd resources/examples/staticlib-test
          ../../../build/c3c -vv static-lib add.c3
          mv add.a libadd.a
          cc test.c -L. -ladd         
          ./a.out
          ../../../build/c3c compile-run test.c3 -L . -l add

      - name: Compile run unit tests
        run: |
          free -h
          cd test
          ../build/c3c compile-test unit -D SLOW_TESTS

      - name: Build testproject
        run: |
          free -h
          cd resources/testproject
          ../../build/c3c run -vvv --trust=full

      - name: run compiler tests
        run: |
          free -h
          cd test
          ../build/c3c compile-run -O1 src/test_suite_runner.c3 -- ../build/c3c test_suite/ 

      - name: bundle_output
        run: |
          mkdir c3
          cp -r lib c3
          cp msvc_build_libraries.py c3
          cp build/c3c c3
          cp README.md c3
          cp releasenotes.md c3
          tar czf c3-android-${{matrix.architecture}}-${{matrix.build_type}}.tar.gz c3

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: c3-android-${{matrix.architecture}}-${{matrix.build_type}}
          path: c3-android-${{matrix.architecture}}-${{matrix.build_type}}.tar.gz
