name: ' ' # empty name
on: [push, pull_request, workflow_dispatch]

jobs:
  broken-ideal:
    runs-on: ubuntu-24.04-arm
    container:
      image: termux/termux-docker:aarch64
      # volumes: 
     #   - /tmp/node20:/__e/node20
    # approximate environment variables for actions that can't be forced to use entrypoint.sh
    env:
      TERMUX_MAIN_PACKAGE_FORMAT: debian
      ANDROID_ROOT: /system
      ANDROID_DATA: /data
      PREFIX: /data/data/com.termux/files/usr
      HOME: /data/data/com.termux/files/home
      PATH: /data/data/com.termux/files/usr/bin
      TMPDIR: /data/data/com.termux/files/usr/tmp
      LANG: en_US.UTF-8
      TZ: UTC
    steps:
      - name: setup
        run: |
          ln -sf ${PREFIX}/etc/termux/mirrors/default ${PREFIX}/etc/termux/chosen_mirrors
          /entrypoint.sh bash -c "yes | pkg upgrade -y"

          /entrypoint.sh pkg install -y ninja clang python git
          # /entrypoint.sh pip install meson
      - uses: actions/checkout@v6.0.1
      - name: build
        run: touch artifact
      - uses: actions/upload-artifact@v6.0.0
        if: always()
        with:
          name: artifact
          path: artifact

